language: php
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer install --no-interaction --optimize-autoloader

script:
   - bin/phpspec run --format=dot
